package com.paymentApp.payment.util;

public class PaymentConstants {

	// Title
	public static final String INVOICE_TTL = "Invoice";
	public static final String INVOICE_CREATED_BROADCASTED_TTL = "Invoice Created & Broadcasted";
	public static final String INVOICE_CLEARED_TTL = "Invoice Cleared";
	public static final String PAYMENT_RECEVIED_TTL = "Amount Received";
	public static final String INVOICE_CREATED_SUCESSFULLY_TTL = "Invoice Created Successfully";
	public static final String INVOICE_GEN_SUCCESS_TTL = "Invoice Generated Successfully";
	public static final String INVOICE_PENDING_TTL = "Invoice Pending For Delivery";
	public static final String INVOICE_RECEIVED_TTL = "Invoice Received For Parcel";
	public static final String PARKING_TIME_END_TTL = "Parking Time Ends!";
	public static final String PARKING_TIME_START_TTL = "Parking Time Started!";

	// Messages
	public static final String INVOICE_CREATED_WITHOUT_PAYER_MSG = "Your invoice of ${Amount} has been broadcasted nearby successfully";
	public static final String INVOICE_CREATED_WITH_PAYER_MSG = "Your invoice of $123 is broadcasted to ${Username}(payerUserName) successfully";
	public static final String INVOICE_PAID_SUCCESS_USER_MSG = "Invoice of $123 has been Paid successfully by \"User Name\"(payerUserName)";
	public static final String PAYMENT_RECEVIED_MSG = "You have received $123 from \"Username\"(payerUserName)";
	public static final String PAYMENT_CREATED_MSG = "Your Invoice of $123 has been created successfully";
	public static final String INVOICE_GEN_WITH_SCAN_MSG = "Invoice Of $123 has been generated by \"Courier Company Name\"(userId). Scan QR/NFC to clear the invoice at the time of delivery";
	public static final String PAYMENT_GEN_TO_PAYER_MSG = "Invoice of $123 has been generated by \"Courier Company Name\"(userId). Amount need to clear by \" User Name\" (payerUserIdName).";
	public static final String PAYMENT_RECEIVED_MSG = "You have received $123 from \"Username\"(payerUserName)";
	public static final String PARKING_TIME_END_MSG = "Your parking time ends on \"Timestamp\" and your amount $123 has been deducted from your wallet.";
	public static final String COMMISSION_RECEIVED_MSG = "You have received $123 from \"Username\"(payerUserName) as a commission";
	public static final String PARKING_TIME_START_MSG = "Your Vehicle has been registered on \"Parking Owner Name\"(UserIdName) at Timestamp\".";
	
	public static final String APP_OWNER_ID = "AOR01";

}
